apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: tcloud-shell
  namespace: tcloud-shell
  labels:
    app: tcloud-shell
spec:
  serviceName: tcloud-shell
  replicas: 1
  selector:
    matchLabels:
      app: tcloud-shell
  template:
    metadata:
      labels:
        app: tcloud-shell
    spec:
      # Node selector to target GPU nodes
      nodeSelector:
        nvidia.com/gpu.present: "true"

      # Tolerate any taints on GPU nodes
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule

      containers:
      - name: tcloud-shell
        image: nvidia/cuda:12.6.0-devel-ubuntu22.04
        command: ["/bin/bash", "/scripts/entrypoint.sh"]

        ports:
        - name: ssh
          containerPort: 22
          protocol: TCP

        resources:
          requests:
            nvidia.com/gpu: 1
            memory: "32Gi"
            cpu: "8"
          limits:
            nvidia.com/gpu: 1
            memory: "64Gi"
            cpu: "16"

        env:
        - name: NVIDIA_VISIBLE_DEVICES
          value: "all"
        - name: NVIDIA_DRIVER_CAPABILITIES
          value: "compute,utility"
        - name: CUDA_HOME
          value: "/usr/local/cuda"
        - name: PATH
          value: "/usr/local/cuda/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"
        - name: LD_LIBRARY_PATH
          value: "/usr/local/cuda/lib64:/usr/local/nvidia/lib64"

        volumeMounts:
        - name: workspace
          mountPath: /workspace
        - name: ssh-keys
          mountPath: /ssh-keys
          readOnly: true
        - name: setup-scripts
          mountPath: /scripts
        - name: dev-shm
          mountPath: /dev/shm

        securityContext:
          privileged: false
          capabilities:
            add:
            - SYS_ADMIN
            - NET_ADMIN

        livenessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3

        readinessProbe:
          tcpSocket:
            port: 22
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3

      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: tcloud-shell-storage
      - name: ssh-keys
        secret:
          secretName: tcloud-shell-ssh-keys
          defaultMode: 0600
      - name: setup-scripts
        configMap:
          name: tcloud-shell-setup
          defaultMode: 0755
      - name: dev-shm
        emptyDir:
          medium: Memory
          sizeLimit: 32Gi
