apiVersion: v1
kind: Service
metadata:
  name: tcloud-web-shell
  namespace: tcloud-shell
  labels:
    app: tcloud-web-shell
spec:
  type: LoadBalancer
  selector:
    app: tcloud-web-shell
  ports:
  - name: http
    port: 80
    targetPort: 7681
    protocol: TCP
  sessionAffinity: ClientIP
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
