{{- if .Values.storage.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "tcloud-shell.fullname" . }}-storage
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tcloud-shell.labels" . | nindent 4 }}
spec:
  accessModes:
    {{- toYaml .Values.storage.accessModes | nindent 4 }}
  {{- if .Values.storage.storageClassName }}
  storageClassName: {{ .Values.storage.storageClassName }}
  {{- end }}
  resources:
    requests:
      storage: {{ .Values.storage.size }}
  {{- if .Values.storage.existingVolume }}
  volumeName: {{ .Values.storage.existingVolume }}
  {{- end }}
{{- end }}
