{{- if .Values.sshShell.enabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tcloud-shell.fullname" . }}-ssh-keys
  namespace: {{ .Values.global.namespace }}
  labels:
    {{- include "tcloud-shell.labels" . | nindent 4 }}
    app.kubernetes.io/component: ssh-shell
type: Opaque
data:
  {{- if .Values.sshShell.authorizedKeys }}
  authorized_keys: {{ .Values.sshShell.authorizedKeys }}
  {{- else }}
  # Placeholder - provide your SSH public key in values.yaml
  # Generate with: cat ~/.ssh/id_rsa.pub | base64
  authorized_keys: ""
  {{- end }}
{{- end }}
